import './globals.css'
import Navbar from '@/components/Navbar'
export const metadata = {
  title: 'Sajan Dev ~ Portfolio Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='myBlue'>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
